### PR TITLE
Update packagechooser.conf

### PR DESCRIPTION
**Pull request by ringo32**
remove qt5-translations lxqt

### CODE REVIEW

**Comment by dalto8** [comment]
Why are we removing this?  Should it be replaced with qt6-translations?

**Comment by ringo32** [comment]
qt6-translations is already needed by qt6-base

**Comment by ringo32** [comment]
qt6-base is needed by lxqt and qt6-translations  is needed bu qt6-base , just by any renaming avoid things making issues of installing, , if install qt6-base al those get installed anyway

**Comment by killajoe** [comment]
https://archlinux.org/packages/extra/x86_64/qt6-base/

Has qt6-translations as dependency.
And lxqt-session depends on kwindowsystem what brings in qt6-base

**Comment by killajoe** [comment]
just see that qterminal is bringing qt5-translations in over qt5.base dependency...  so removing it from the list will not even change anything ...

**Comment by killajoe** [comment]
we should still remove it from the list as of new version of qterminal will depend fully on qt6, what will make the package obsolete for lxqt.

**Review by killajoe — APPROVED** [review]

**Pull request merged**
