### PR TITLE
should we add timeouts?

### PR DESCRIPTION
**Pull request by killajoe**
would make the process more stable, as also if something takes longer it will not stop installs

### CODE REVIEW

**Comment by killajoe** [comment]
https://github.com/calamares/calamares/issues/2085

**Comment by dalto8** [comment]
I think it is a good idea but 30 minutes seems like too much.  We don't want to hang the install.

This is probably timing out on offline installs where mkinitcpio is running when ucode is removed.  How about 3 minutes instead of 30 minutes?

**Comment by killajoe** [comment]
> How about 3 minutes instead of 30 minutes?

it will not stretch install if it is working well only if something is not working it will leave it till the timeout period.. seems 3 Minutes seem a bit low to me. If we take a higher one like 10 minutes we do not need to adjust again in case ?  i set them to 30 Minutes to be save and forget.

**Comment by dalto8** [comment]
> it will not stretch install if it is working well only if something is not working it will leave it till the timeout period.. seems 3 Minutes seem a bit low to me. If we take a higher one like 10 minutes we do not need to adjust again in case ? i set them to 30 Minutes to be save and forget.

My opinion is that a timeout should be appropriate for the task.  We shouldn't set them to be really long and cause people to have a long wait before a failure.  They should set to be slightly longer than what we think the longest run could be.

In this case, the task is removing a package and mkinitcpio run for a single kernel in an offline install.  30 seconds is probably right at the edge in a resource constrained environment.  1 minute is probably a reasonable timeout here that would work fine.  3 minutes is already extremely conservative in my opinion.  

Is there a realistic scenario where this task could take longer than that?  Forcing a user to wait an extra 10 minutes for something to fail seems unreasonable.

**Comment by killajoe** [comment]
Should would and will do are not the terms working in any real use case..   Hardware is causing hickups e.t.c.  
I will not go discuss 3 Minutes against 10. ;)

**Pull request closed without merging**
