### PR TITLE
fix for theming seperation for all DEs

### PR DESCRIPTION
**Pull request by killajoe**
adding separation for theming/settings packages to all DEs to make it easy to unselect:

### CODE REVIEW

**Comment by dalto8** [comment]
I like the idea but I think it is confusing like that.  It makes the DEs too nested.

What if we put it inside the DE instead of at the same level?

**Comment by dalto8** [comment]
I think something like this would be better for a few reasons:
* We don't really want people unselecting the theming unless they know what they are doing
* I think we are calling too much attention to the option the other way
* It stops the actual DE list from being under two options

image

**Comment by killajoe** [comment]
To be true you are right on that we do not want users to not install the settings we add to fix stuff they was complaining about in the first place. And also if we do not change it it is possible to not install the settings/theming by selecting the packages. On the other side I have had exactly the same for xfce4 for long time already. 
It would look the same as long as you do not start editing packages:





Could be needed to improve the given information and not call it theming may keep the same as for the packages and call it settings..
But i would agree more to not change it at all, which would also keep the format cleaner and easier to handle. i would now more like to remove the subgroup from xfce4 too would be more consequent. ;)

**Comment by dalto8** [comment]
Doesn't alternative above provide a "best of both worlds"?  Give them the ability to easily uncheck the theming as a group without the nesting situation?

**Comment by killajoe** [comment]
> Doesn't alternative above provide a "best of both worlds"? Give them the ability to easily uncheck the theming as a group without the nesting situation?
yes it would not show up like "I HAVE TO CLICK" how this is formatted in yaml?
(so i can see how it looks in real live ; )

**Comment by dalto8** [comment]
```
- name: "KDE-Desktop"
  description: "KDE-Plasma Desktop - Simple by default, powerful when needed."
  hidden: false
  selected: false
  critical: true
  subgroups:
      - name: "EndeavourOS Theming"
        description: "EndeavourOS plasma theming (unselect to install vanilla)"
        selected: false
        packages:
            - eos-plasma-sddm-config
            - eos-settings-plasma
  packages:
    - ark
    - audiocd-kio
    - bluedevil
    - breeze-gtk
    - dolphin
    - gwenview
    - kcalc
    - kate
    - kdeconnect
    - kde-gtk-config
    - khotkeys
    - kinfocenter
    - kinit
    - kio-fuse
    - konsole
    - kscreen
    - kwallet-pam
    - okular
    - plasma-desktop
    - plasma-disks
    - plasma-nm
    - plasma-pa
    - powerdevil
    - print-manager
    - sddm-kcm
    - solid
    - spectacle
    - xsettingsd
```

**Comment by killajoe** [comment]
oh yes i like yaml exactly for this ;)

**Comment by killajoe** [comment]
This is a good middleway..   i will go to reformat soon..

**Pull request closed without merging**
