### PR TITLE
Change all occurences of se to sv

### PR DESCRIPTION
**Pull request by BenjaminLindberg**

### CODE REVIEW

**Comment by killajoe** [comment]
hmm thats from community editions we do not have these in current usage.. from what i see the used parts are all updated to use [sv]

**Comment by BenjaminLindberg** [comment]
@killajoe then what is that file? It's facts that that file uses se instead of sv, but is that file even in use then? I'm confused

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/calamares/commit/5b9ad8d397f8f918a4010f1bf097472157c1c66b
should resolve this, thanks for hinting anyway.

**Comment by killajoe** [comment]
> @killajoe then what is that file? It's facts that that file uses se instead of sv, but is that file even in use then? I'm confused 

The parts were marked as archived already and was not used anymore, I removed this parts now so only used translations are in there now. These all are using correct [sv]
Check latest commit.

**Pull request closed without merging**
